### ISSUE TITLE
Repository is incomplete

### ISSUE THREAD

**Issue by dshadoff** [jbrandwood/teos#1]
Repository contains substantial, but incomplete, code.

Example: teos.s has includes for:
		include	"teos_bank0.s"
		include	"teos_bank1.s"
		include	"teos_bank2.s"
		include	"teos_bank3.s"

...However, "teos_bank1.s" and "teos_bank2.s" are not in the repository, and do not appear to be built as part of the build process.

**Comment by jbrandwood** [comment]
Not anymore! ;-)
