### ISSUE TITLE
Turbo Everdrive Pro support

### ISSUE THREAD

**Issue by Peredonov** [jbrandwood/teos#11]
Is it possible for TEOS to be used in a new Turbo Everdrive Pro? I tried loading the TEOS.pce file, with the required files in a TBED folder but TEOS fails to load. Krikzz's new OS uses a "edturbo" folder instead of TBED (tried putting all the BIN files there just in case, but it also didn't work).

**Comment by jbrandwood** [comment]
The TED Pro is completely different hardware, so sorry, no it's not even slightly compatible with TEOS.

Now, there *may* be a version of TEOS for the TED Pro at some point in the future, but I have lots of other things to work on before that.
