### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Pistacchione** [jbrandwood/teos#8]
Hi,

There is place where I can download a compiled version, or there is some instruction of how I can use it inside the Turbo Everdrive?

Thanks 😄

**Comment by jbrandwood** [comment]
There are a lot of recent changes in TEOS that are still being tested, and so I don't consider it ready for another public release at the moment. But if you're a developer, then feel free to grab the source, build it, and give it a go! :-)

If you're just looking to use the most-recent stable version of TEOS on your Turbo Everdrive v2, then you can find some instructions and a link to it on Krikzz's forum here ..

https://krikzz.com/forum/index.php?topic=10726.0

**Comment by Pistacchione** [comment]
Thanks for quick response

I'll grab the newest one from the above link thanks!

About building the source code there are some specific tools and or command that we need to do in order to have a functional "handmade" build?

**Comment by jbrandwood** [comment]
Sorry, I got distracted!

TEOS requies the PCEAS assembler from the HuC repository in order to build it.

There's only a Windows batch file, and not a Makefile, because I'm the only person actually working on TEOS.

**Comment by Pistacchione** [comment]
Ok, thank you very much for your information and for this cool project!
